-- ============================================
-- GOLF CHARITY REWARDS PLATFORM - DATABASE SCHEMA
-- ============================================
-- Run this file once in your Supabase SQL Editor
-- (Supabase Dashboard -> SQL Editor -> paste this -> Run)
-- ============================================

-- 1. USERS TABLE
-- Stores normal users who register on the platform
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,        -- stored as a bcrypt hash, never plain text
  charity_id INTEGER,                     -- which charity the user supports (set after charities table exists)
  created_at TIMESTAMP DEFAULT NOW()
);

-- 2. CHARITIES TABLE
-- List of charities users can choose to support
CREATE TABLE charities (
  id SERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description TEXT,
  donation_percentage INTEGER DEFAULT 10, -- % of prize that goes to this charity
  created_at TIMESTAMP DEFAULT NOW()
);

-- Now that charities exists, link users.charity_id to it
ALTER TABLE users
  ADD CONSTRAINT fk_user_charity
  FOREIGN KEY (charity_id) REFERENCES charities(id)
  ON DELETE SET NULL;

-- 3. SUBSCRIPTIONS TABLE
-- Tracks each user's subscription plan and status
CREATE TABLE subscriptions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_type VARCHAR(20) NOT NULL CHECK (plan_type IN ('monthly', 'yearly')),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired')),
  start_date TIMESTAMP DEFAULT NOW(),
  end_date TIMESTAMP NOT NULL
);

-- 4. SCORES TABLE
-- Each user can have at most 5 scores stored (oldest removed automatically by backend logic)
CREATE TABLE scores (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 45),
  score_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (user_id, score_date)   -- only one score per date per user
);

-- 5. DRAWS TABLE
-- Each time the admin runs a draw, one row is created here
CREATE TABLE draws (
  id SERIAL PRIMARY KEY,
  draw_date TIMESTAMP DEFAULT NOW(),
  winning_numbers INTEGER[] NOT NULL,     -- the 5 randomly generated numbers
  prize_pool NUMERIC(12, 2) NOT NULL DEFAULT 100000,
  jackpot_rolled_over BOOLEAN DEFAULT FALSE -- true if no 5-match winner this round
);

-- 6. DRAW_RESULTS TABLE
-- Stores which users won, how many numbers matched, and their prize share
CREATE TABLE draw_results (
  id SERIAL PRIMARY KEY,
  draw_id INTEGER NOT NULL REFERENCES draws(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  match_count INTEGER NOT NULL CHECK (match_count IN (3, 4, 5)),
  prize_amount NUMERIC(12, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 7. WINNER_PROOFS TABLE
-- Winners upload a screenshot as proof, admin approves/rejects it
CREATE TABLE winner_proofs (
  id SERIAL PRIMARY KEY,
  draw_result_id INTEGER NOT NULL REFERENCES draw_results(id) ON DELETE CASCADE,
  proof_image_url VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  uploaded_at TIMESTAMP DEFAULT NOW()
);

-- 8. PAYMENTS TABLE
-- Tracks whether a winner has actually been paid
CREATE TABLE payments (
  id SERIAL PRIMARY KEY,
  draw_result_id INTEGER NOT NULL REFERENCES draw_results(id) ON DELETE CASCADE,
  amount NUMERIC(12, 2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'paid')),
  paid_at TIMESTAMP
);

-- 9. ADMIN_USERS TABLE
-- Separate table for admin login (kept simple & separate from normal users)
CREATE TABLE admin_users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- SEED DATA (sample charities + one admin login)
-- ============================================

INSERT INTO charities (name, description, donation_percentage) VALUES
('Save The Children', 'Supporting children education and welfare', 10),
('WWF Wildlife Fund', 'Protecting wildlife and natural habitats', 15),
('Red Cross', 'Emergency relief and disaster response', 12);

-- Default admin login: email = admin@golfcharity.com / password = admin123
-- (password below is a bcrypt hash of "admin123" — generated by the backend setup script)
-- We insert this via the seed script instead of here, since SQL editor can't run bcrypt.
